name: C++ CI

on:
  pull_request:
    branches: [ "main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          c-compiler: gcc
          cxx-compiler: g++

      - name: Build Project
        run: |
          g++ --version
          cmake --build build

      - name: Test Project
        run: ctest --test-dir build

  generate-documentation:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: |
          ls -l
          cd docs
          doxygen Doxyfile

      - name: Create separate branch for Doxygen docs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
               
          git checkout -b doxygen-docs
          git rm -r --cached .
          git add -f docs
          git commit -m "Generated Doxygen documentation"
          git push --force origin doxygen-docs
